# Generated by Django 3.1.1 on 2020-10-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=10)),
                ('sequence', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('spot_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('my_course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=50)),
                ('my_course_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=10)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.user')),
            ],
        ),
    ]
